version: '3'

services:
  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.9.0
    hostname: wazuh.indexer
    container_name: wazuh.indexer
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Limited for the G2 Laptop
      - "discovery.type=single-node"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: on-failure

  wazuh.manager:
    image: wazuh/wazuh-manager:4.9.0
    hostname: wazuh.manager
    container_name: wazuh.manager
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword123!
    volumes:
      - wazuh-manager-data:/var/ossec/api/configuration
      - wazuh-manager-logs:/var/ossec/logs
      - wazuh-manager-integrations:/var/ossec/integrations
      - wazuh-manager-active-response:/var/ossec/active-response/bin
      - wazuh-manager-agentless:/var/ossec/agentless
      - wazuh-manager-wodles:/var/ossec/wodles
      - wazuh-manager-file:/var/ossec/etc/shared
    depends_on:
      - wazuh.indexer
    restart: on-failure

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.9.0
    hostname: wazuh.dashboard
    container_name: wazuh.dashboard
    ports:
      - "443:5601"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword123!
      - WAZUH_API_URL=https://wazuh.manager:55000
    depends_on:
      - wazuh.indexer
      - wazuh.manager
    volumes:
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
    restart: on-failure

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:
  wazuh-manager-logs:
  wazuh-manager-integrations:
  wazuh-manager-active-response:
  wazuh-manager-agentless:
  wazuh-manager-wodles:
  wazuh-manager-file:
  wazuh-dashboard-config:
